[project]
name = "hass-eaton-ups-mqtt"
version = "0.2.2"
description = "Home Assistant integration for Eaton UPS devices via MQTT"
authors = [
    { name = "lnagel" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.13"
dependencies = [
    "colorlog==6.10.1",
    "homeassistant>=2025.3.1",
    "paho-mqtt==2.1.0",
    "ruff==0.14.10",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0.0",
    "pytest-homeassistant-custom-component>=0.13.0",
]

[tool.uv]
package = false

[tool.black]
line-length = 88
target-version = ["py313"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | build
  | dist

)/
'''
